language: node_js

node_js:
 - 0.8

notifications:
  email:
    - lloyd@mozilla.com
    - zcarter@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#identity"
    use_notice: false
    skip_join: false
